env: 
  - global:
    - M2_HOME=./target/apache-maven-3.0.5
    - PATH=$M2_HOME/bin:$PATH

install:
  - mkdir -p target
  - cd target
  - wget http://apache.mirrors.pair.com/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
  - tar zxf apache-maven-3.0.5-bin.tar.gz

language: java
jdk: oraclejdk7
